default:
  resources:
    requests:
      memory: "50Mi"
      cpu: "256m"
    limits:
      memory: "100Mi"
      cpu: "512m"

client:
  service: 
    type: "ClusterIP"
    port: 80
  port: 80
  image:
    repository: "rivkayo/triviawater"
    tag: "1.9"
    pullPolicy: IfNotPresent
  replicaCount: 3

server:
  service: 
    type: "ClusterIP"
    port: 8080
  port: 2024
  image:
    repository: "rivkayo/triviawaterserver"
    tag: "1.4"
  replicaCount: 3

database:
  service: 
    type: "ClusterIP"
    port: 3306
  mysql:
    resources:
      requests:
        memory: "512Mi"
        cpu: "256m"
      limits:
        memory: "1Gi"
        cpu: "512m"
    DB_HOST: "database-service"
    DB_PORT: 3306
    DB_NAME: "trivia_water"
    image:
      repository: "rivkayo/triviawaterdatabase"
      tag: "1.0"
    replicaCount: 1

service:
  type: ClusterIP
  clientPort: 8080
  serverPort: 8081

ingress:
  enabled: true
  host: "myapp.example.com"
  paths:
    - /client
    - /server