default:
  resources:
    requests:
      memory: "50mi"
      cpu: "256m"
    limits:
      memory: "100mi"
      cpu: "512m"

client:
  image:
    repository: rivkayo/triviawater
    tag: 1.6
    pullPolicy: IfNotPresent #if img not in pod
  replicaCount: 3

server:
  image:
    repository: rivkayo/triviawaterserver
    tag: 1.1
    pullPolicy: IfNotPresent
  replicaCount: 3

database:
  mysql:
    DB_HOST: localhost
    DB_PORT: 3306
    DB_NAME: trivia_water
    image:
        repository: rivkayo/triviawaterdatabase
        tag: 1.0
        pullPolicy: IfNotPresent
      replicaCount: 1

service:
  type: ClusterIP
  clientPort: 8080
  serverPort: 8081

ingress:
  enabled: true
  host: myapp.example.com
  paths:
    - /client
    - /server
