# Add/update these sections:
openshift:
  enabled: false # Disable all OpenShift features

route:
  enabled: false # Explicitly disable routes

ingress:
  enabled: false # Disable ingress unless needed

services:
  client:
    type: NodePort # Change from ClusterIP for test access
    port: 80
    nodePort: 30080 # Optional fixed port (30000-32767)

  # Keep other services as ClusterIP
  server:
    type: ClusterIP
    port: 8080

  database:
    type: ClusterIP
    port: 3306
