apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-privileged-sa
  namespace: training
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: my-chart-release
    meta.helm.sh/release-namespace: training
