apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-database # Name of the deployment
  labels:
    app: database-app
spec:
  replicas: {{ .Values.database.replicaCount }} # Set the number of replicas based on values.yaml
  selector:
    matchLabels:
      app: deployment-database
  strategy:
    type: RollingUpdate # Rolling update strategy
    rollingUpdate:
      maxSurge: 1 # Max number of Pods to be created over the desired replicas
      maxUnavailable: 1 # Max number of Pods that can be unavailable during the update
  template:
    metadata:
      labels:
        app: deployment-database
    spec:
      containers:
        - name: database
          image: "{{ .Values.database.mysql.image.repository }}:{{ .Values.database.mysql.image.tag }}" # Image from values.yaml
          ports:
            - containerPort: {{ .Values.database.mysql.DB_PORT }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-db          # Ensure the Secret 'secret-db' exists
                  key: DB_PASSWORD         # Ensure the key 'DB_PASSWORD' exists in the Secret

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap-db       # Ensure the ConfigMap 'configmap-db' exists
                  key: DB_NAME             # Ensure the key 'DB_NAME' exists in the ConfigMap
          resources:
            requests:
              memory: {{ .Values.default.resources.requests.memory }}
              cpu: {{ .Values.default.resources.requests.cpu }}
            limits:
              memory: {{ .Values.default.resources.limits.memory }}
              cpu: {{ .Values.default.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.database.mysql.DB_PORT }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.database.mysql.DB_PORT }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.database.mysql.DB_PORT }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 7
            failureThreshold: 10