apiVersion: v1
kind: Secret
metadata:
  name: secret-db
  namespace: training  # Ensure the namespace is specified
  labels:
    app.kubernetes.io/managed-by: Helm  # Add this label
  annotations:
    meta.helm.sh/release-name: 'my-chart-release' # Add this annotation
    meta.helm.sh/release-namespace: 'training'  # Add this annotation
data:
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: ejEwbXoxMG0=
  MYSQL_ROOT_PASSWORD: ejEwbXoxMG0=


