apiVersion: v1
kind: Secret
metadata:
  name: { { .Values.database.mysql.auth.existingSecret } }
type: Opaque
data:
  database:
  mysql:
    auth:
      DB_USERNAME: cm9vdA==
      DB_PASSWORD: ejEwbXoxMG0=
