apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database-service
spec:
  type: { { .Values.database.service.type } }
  ports:
    - port: { { .Values.database.service.port } }
      targetPort: { { .Values.database.port } }
      protocol: TCP
  selector:
    app: database-service
