apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database-service
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: my-chart-release
    meta.helm.sh/release-namespace: training 
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.mysql.DB_PORT }}
      protocol: TCP
  selector:
    app: database-app
