apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app # Name of the deployment
  labels:
    app: client-app
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: client-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: client-app
    spec:
      serviceAccountName: my-privileged-sa
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 0
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          ports:
            - containerPort: {{ .Values.client.port }}
          resources:
            requests:
              memory: "{{ .Values.default.resources.requests.memory }}"
              cpu: "{{ .Values.default.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.default.resources.limits.memory }}"
              cpu: "{{ .Values.default.resources.limits.cpu }}"
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.client.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.client.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.client.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 10
