apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client-service
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: my-chart-release
    meta.helm.sh/release-namespace: training
spec:
  selector:
    app: client-app
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.port }}
      protocol: TCP
