apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client-service
spec:
  selector:
    app: client-app
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.port }}
      protocol: TCP
