apiVersion: v1
kind: Service
metadata:
  name: main-server-service
  labels:
    app: main-server-service
spec:
  type: { { .Values.server.service.type } }
  ports:
    - port: { { .Values.server.service.port } }
      targetPort: { { .Values.server.port } }
      protocol: TCP
  selector:
    app: main-server-service
