apiVersion: v1
kind: Service
metadata:
  name: main-server-service
  labels:
    app: main-server-service
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: my-chart-release
    meta.helm.sh/release-namespace: training
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
  selector:
    app: deployment-server